name: portal
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - asn1crypto
  - blinker
  - cachetools
  - certifi
  - cffi
  - chardet
  - Click
  - cryptography
  - dominate
  - Flask
  - Flask-Bootstrap
  - Flask-Login
  - Flask-Mail
  - Flask-Moment
  - Flask-SQLAlchemy
  - Flask-WTF
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - httplib2
  - idna
  - itsdangerous
  - Jinja2
  - MarkupSafe
  - numpy
  - oauth2client
  - pandas
  - pyasn1
  - pyasn1-modules
  - pycparser
  - PyMySQL
  - python-dateutil
  - python-dotenv
  - pytz
  - rauth
  - requests
  - rsa
  - six
  - SQLAlchemy
  - uritemplate
  - urllib3
  - visitor
  - Werkzeug
  - WTForms
  - networkx
